digitalio: Improve DigitalInOut constructor, add finaliser
Now it's possible to construct outputs or enable pulls immediately:

```py
>>> d = digitalio.DigitalInOut(board.A0, pull=digitalio.Pull.UP)
>>> d.pull
digitalio.Pull.UP
```

```py
>>> d = digitalio.DigitalInOut(board.A0, value=True)
>>> d.direction
digitalio.Direction.OUTPUT
>>> d.value
True
```

```py
>>> d = digitalio.DigitalInOut(board.A0, value=False, drive_mode=digitalio.DriveMode.OPEN_DRAIN)
>>> d.drive_mode
digitalio.DriveMode.OPEN_DRAIN
```

The finaliser means that if a pin object is allowed to go out of scope,
then it will be deinitialized automatically when GC runs. **this is a
potential incompatibility**: some hypothetical code that intentionally
leaked a pin might function differently, i.e.
```py
digitalio.DigitalInOut(board.A0).switch_to_output(True)
```
as a way to stick a pin in output mode indefinitely will no longer work
(but may still appear to work "for awhile" because gc doesn't run right
away).

I made this change in part because it simplifies error handling in the
constructor: An incorrect argument would otherwise have left the pin
stuck in allocated state until the interpreter was reset; with this
change, it's available again though not until the GC runs so it would
remain perplexing in interactive situations:
```py
>>> d = digitalio.DigitalInOut(board.A0, pull=7)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pull must be of type Pull or None, not int
>>> d = digitalio.DigitalInOut(board.A0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: A0 in use
>>> gc.collect()
>>> d = digitalio.DigitalInOut(board.A0)
>>> d
<DigitalInOut>
```